# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: mvn test  
     - uses: actions/setup-java@v2
       with:
        java-version: '11'
        distribution: 'adopt'
